package movieapp.persistance;

import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDate;

import javax.persistence.EntityManager;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import movieapp.entity.Person;

@DataJpaTest
class PersonRepositoryTest {

	@Autowired
	PersonRepository personRepository;
	
	@Autowired
	EntityManager entityManager;
	
	@Test
	void testSave() {
		saveAssertPerson("Steve McQueen", LocalDate.of(1930, 3, 24), null);
	}

	private void saveAssertPerson(String title, LocalDate birthday, LocalDate deathday) {
		Person person = new Person("Steve McQueen", LocalDate.of(1930, 3, 24), null);
		// when
		personRepository.save(person);
		// then
		var idPerson = person.getId();
		assertNotNull(idPerson, "id generated by database");
	}
}
